oomp_word_dict = {}
oomp_word_dict_words = []

oomp_word_dict_words.append("bowtie")
oomp_word_dict_words.append("smile")
#oomp_word_dict_words.append("laughing")
oomp_word_dict_words.append("blush")
#oomp_word_dict_words.append("smiley")
#oomp_word_dict_words.append("relaxed")
#oomp_word_dict_words.append("smirk")
#oomp_word_dict_words.append("heart_eyes")
#oomp_word_dict_words.append("kissing_heart")
#oomp_word_dict_words.append("kissing_closed_eyes")
#oomp_word_dict_words.append("flushed")
#oomp_word_dict_words.append("relieved")
#oomp_word_dict_words.append("satisfied")
oomp_word_dict_words.append("grin")
oomp_word_dict_words.append("wink")
#oomp_word_dict_words.append("stuck_out_tongue_winking_eye")
#oomp_word_dict_words.append("stuck_out_tongue_closed_eyes")
#oomp_word_dict_words.append("grinning")
oomp_word_dict_words.append("kissing")
#oomp_word_dict_words.append("kissing_smiling_eyes")
#oomp_word_dict_words.append("stuck_out_tongue")
oomp_word_dict_words.append("sleeping")
#oomp_word_dict_words.append("worried")
#oomp_word_dict_words.append("frowning")
#oomp_word_dict_words.append("anguished")
#oomp_word_dict_words.append("open_mouth")
#oomp_word_dict_words.append("grimacing")
#oomp_word_dict_words.append("confused")
#oomp_word_dict_words.append("hushed")
#oomp_word_dict_words.append("expressionless")
#oomp_word_dict_words.append("unamused")
#oomp_word_dict_words.append("sweat_smile")
#oomp_word_dict_words.append("sweat")
#oomp_word_dict_words.append("disappointed_relieved")
#oomp_word_dict_words.append("weary")
#oomp_word_dict_words.append("pensive")
#oomp_word_dict_words.append("disappointed")
#oomp_word_dict_words.append("confounded")
#oomp_word_dict_words.append("fearful")
#oomp_word_dict_words.append("cold_sweat")
#oomp_word_dict_words.append("persevere")
oomp_word_dict_words.append("cry")
#oomp_word_dict_words.append("sob")
#oomp_word_dict_words.append("joy")
#oomp_word_dict_words.append("astonished")
oomp_word_dict_words.append("scream")
#oomp_word_dict_words.append("neckbeard")
#oomp_word_dict_words.append("tired_face")
oomp_word_dict_words.append("angry")
#oomp_word_dict_words.append("rage")
#oomp_word_dict_words.append("triumph")
oomp_word_dict_words.append("sleepy")
#oomp_word_dict_words.append("yum")
#oomp_word_dict_words.append("mask")
oomp_word_dict_words.append("sunglasses")
#oomp_word_dict_words.append("dizzy_face")
#oomp_word_dict_words.append("imp")
#oomp_word_dict_words.append("smiling_imp")
#oomp_word_dict_words.append("neutral_face")
#oomp_word_dict_words.append("no_mouth")
#oomp_word_dict_words.append("innocent")
oomp_word_dict_words.append("alien")
#oomp_word_dict_words.append("yellow_heart")
#oomp_word_dict_words.append("blue_heart")
#oomp_word_dict_words.append("purple_heart")
oomp_word_dict_words.append("heart")
#oomp_word_dict_words.append("green_heart")
#oomp_word_dict_words.append("broken_heart")
#oomp_word_dict_words.append("heartbeat")
#oomp_word_dict_words.append("heartpulse")
#oomp_word_dict_words.append("two_hearts")
#oomp_word_dict_words.append("revolving_hearts")
oomp_word_dict_words.append("cupid")
#oomp_word_dict_words.append("sparkling_heart")
oomp_word_dict_words.append("sparkles")
oomp_word_dict_words.append("star")
#oomp_word_dict_words.append("star2")
oomp_word_dict_words.append("dizzy")
#oomp_word_dict_words.append("boom")
#oomp_word_dict_words.append("collision")
oomp_word_dict_words.append("anger")
#oomp_word_dict_words.append("exclamation")
oomp_word_dict_words.append("question")
#oomp_word_dict_words.append("grey_exclamation")
#oomp_word_dict_words.append("grey_question")
#oomp_word_dict_words.append("zzz")
#oomp_word_dict_words.append("dash")
#oomp_word_dict_words.append("sweat_drops")
#oomp_word_dict_words.append("notes")
#oomp_word_dict_words.append("musical_note")
oomp_word_dict_words.append("fire")
#oomp_word_dict_words.append("hankey")
oomp_word_dict_words.append("poop")
#oomp_word_dict_words.append("shit")
#oomp_word_dict_words.append("+1")
oomp_word_dict_words.append("thumbsup")
#oomp_word_dict_words.append("-1")
oomp_word_dict_words.append("thumbsdown")
#oomp_word_dict_words.append("ok_hand")
#oomp_word_dict_words.append("punch")
#oomp_word_dict_words.append("facepunch")
#oomp_word_dict_words.append("fist")
#oomp_word_dict_words.append("v")
#oomp_word_dict_words.append("wave")
oomp_word_dict_words.append("hand")
#oomp_word_dict_words.append("raised_hand")
#oomp_word_dict_words.append("open_hands")
#oomp_word_dict_words.append("point_up")
#oomp_word_dict_words.append("point_down")
#oomp_word_dict_words.append("point_left")
#oomp_word_dict_words.append("point_right")
#oomp_word_dict_words.append("raised_hands")
oomp_word_dict_words.append("pray")
#oomp_word_dict_words.append("point_up_2")
oomp_word_dict_words.append("clap")
oomp_word_dict_words.append("muscle")
#oomp_word_dict_words.append("metal")
#oomp_word_dict_words.append("fu")
#oomp_word_dict_words.append("walking")
#oomp_word_dict_words.append("runner")
#oomp_word_dict_words.append("running")
#oomp_word_dict_words.append("couple")
#oomp_word_dict_words.append("family")
#oomp_word_dict_words.append("two_men_holding_hands")
#oomp_word_dict_words.append("two_women_holding_hands")
oomp_word_dict_words.append("dancer")
#oomp_word_dict_words.append("dancers")
#oomp_word_dict_words.append("ok_woman")
#oomp_word_dict_words.append("no_good")
#oomp_word_dict_words.append("information_desk_person")
#oomp_word_dict_words.append("raising_hand")
#oomp_word_dict_words.append("bride_with_veil")
#oomp_word_dict_words.append("person_with_pouting_face")
#oomp_word_dict_words.append("person_frowning")
#oomp_word_dict_words.append("bow")
#oomp_word_dict_words.append("couplekiss")
#oomp_word_dict_words.append("couple_with_heart")
#oomp_word_dict_words.append("massage")
#oomp_word_dict_words.append("haircut")
#oomp_word_dict_words.append("nail_care")
#oomp_word_dict_words.append("boy")
#oomp_word_dict_words.append("girl")
#oomp_word_dict_words.append("woman")
#oomp_word_dict_words.append("man")
oomp_word_dict_words.append("baby")
#oomp_word_dict_words.append("older_woman")
#oomp_word_dict_words.append("older_man")
#oomp_word_dict_words.append("person_with_blond_hair")
#oomp_word_dict_words.append("man_with_gua_pi_mao")
#oomp_word_dict_words.append("man_with_turban")
#oomp_word_dict_words.append("construction_worker")
#oomp_word_dict_words.append("cop")
oomp_word_dict_words.append("angel")
oomp_word_dict_words.append("princess")
#oomp_word_dict_words.append("smiley_cat")
#oomp_word_dict_words.append("smile_cat")
#oomp_word_dict_words.append("heart_eyes_cat")
#oomp_word_dict_words.append("kissing_cat")
#oomp_word_dict_words.append("smirk_cat")
#oomp_word_dict_words.append("scream_cat")
#oomp_word_dict_words.append("crying_cat_face")
#oomp_word_dict_words.append("joy_cat")
#oomp_word_dict_words.append("pouting_cat")
#oomp_word_dict_words.append("japanese_ogre")
#oomp_word_dict_words.append("japanese_goblin")
#oomp_word_dict_words.append("see_no_evil")
#oomp_word_dict_words.append("hear_no_evil")
#oomp_word_dict_words.append("speak_no_evil")
#oomp_word_dict_words.append("guardsman")
oomp_word_dict_words.append("skull")
oomp_word_dict_words.append("feet")
oomp_word_dict_words.append("lips")
oomp_word_dict_words.append("kiss")
oomp_word_dict_words.append("droplet")
oomp_word_dict_words.append("ear")
oomp_word_dict_words.append("eyes")
oomp_word_dict_words.append("nose")
oomp_word_dict_words.append("tongue")
#oomp_word_dict_words.append("love_letter")
#oomp_word_dict_words.append("bust_in_silhouette")
#oomp_word_dict_words.append("busts_in_silhouette")
#oomp_word_dict_words.append("speech_balloon")
#oomp_word_dict_words.append("thought_balloon")
#oomp_word_dict_words.append("feelsgood")
#oomp_word_dict_words.append("finnadie")
#oomp_word_dict_words.append("goberserk")
#oomp_word_dict_words.append("godmode")
#oomp_word_dict_words.append("hurtrealbad")
#oomp_word_dict_words.append("rage1")
#oomp_word_dict_words.append("rage2")
#oomp_word_dict_words.append("rage3")
#oomp_word_dict_words.append("rage4")
#oomp_word_dict_words.append("suspect")
#oomp_word_dict_words.append("trollface")
oomp_word_dict_words.append("sunny")
oomp_word_dict_words.append("umbrella")
oomp_word_dict_words.append("cloud")
oomp_word_dict_words.append("snowflake")
oomp_word_dict_words.append("snowman")
oomp_word_dict_words.append("zap")
oomp_word_dict_words.append("cyclone")
oomp_word_dict_words.append("foggy")
oomp_word_dict_words.append("ocean")
oomp_word_dict_words.append("cat")
oomp_word_dict_words.append("dog")
oomp_word_dict_words.append("mouse")
oomp_word_dict_words.append("hamster")
oomp_word_dict_words.append("rabbit")
oomp_word_dict_words.append("wolf")
oomp_word_dict_words.append("frog")
oomp_word_dict_words.append("tiger")
oomp_word_dict_words.append("koala")
oomp_word_dict_words.append("bear")
oomp_word_dict_words.append("pig")
#oomp_word_dict_words.append("pig_nose")
oomp_word_dict_words.append("cow")
#oomp_word_dict_words.append("boar")
#oomp_word_dict_words.append("monkey_face")
oomp_word_dict_words.append("monkey")
oomp_word_dict_words.append("horse")
oomp_word_dict_words.append("racehorse")
oomp_word_dict_words.append("camel")
oomp_word_dict_words.append("sheep")
oomp_word_dict_words.append("elephant")
oomp_word_dict_words.append("panda_face")
oomp_word_dict_words.append("snake")
oomp_word_dict_words.append("bird")
oomp_word_dict_words.append("baby_chick")
oomp_word_dict_words.append("hatched_chick")
oomp_word_dict_words.append("hatching_chick")
oomp_word_dict_words.append("chicken")
oomp_word_dict_words.append("penguin")
oomp_word_dict_words.append("turtle")
oomp_word_dict_words.append("bug")
oomp_word_dict_words.append("honeybee")
oomp_word_dict_words.append("ant")
oomp_word_dict_words.append("beetle")
oomp_word_dict_words.append("snail")
oomp_word_dict_words.append("octopus")
#oomp_word_dict_words.append("tropical_fish")
oomp_word_dict_words.append("fish")
oomp_word_dict_words.append("whale")
#oomp_word_dict_words.append("whale2")
oomp_word_dict_words.append("dolphin")
#oomp_word_dict_words.append("cow2")
oomp_word_dict_words.append("ram")
oomp_word_dict_words.append("rat")
oomp_word_dict_words.append("water_buffalo")
#oomp_word_dict_words.append("tiger2")
#oomp_word_dict_words.append("rabbit2")
oomp_word_dict_words.append("dragon")
oomp_word_dict_words.append("goat")
oomp_word_dict_words.append("rooster")
#oomp_word_dict_words.append("dog2")
#oomp_word_dict_words.append("pig2")
#oomp_word_dict_words.append("mouse2")
oomp_word_dict_words.append("ox")
#oomp_word_dict_words.append("dragon_face")
oomp_word_dict_words.append("blowfish")
oomp_word_dict_words.append("crocodile")
#oomp_word_dict_words.append("dromedary_camel")
oomp_word_dict_words.append("leopard")
#oomp_word_dict_words.append("cat2")
oomp_word_dict_words.append("poodle")
#oomp_word_dict_words.append("paw_prints")
oomp_word_dict_words.append("bouquet")
#oomp_word_dict_words.append("cherry_blossom")
oomp_word_dict_words.append("tulip")
#oomp_word_dict_words.append("four_leaf_clover")
oomp_word_dict_words.append("rose")
oomp_word_dict_words.append("sunflower")
#oomp_word_dict_words.append("hibiscus")
oomp_word_dict_words.append("maple_leaf")
oomp_word_dict_words.append("leaves")
#oomp_word_dict_words.append("fallen_leaf")
oomp_word_dict_words.append("herb")
oomp_word_dict_words.append("mushroom")
oomp_word_dict_words.append("cactus")
oomp_word_dict_words.append("palm_tree")
#oomp_word_dict_words.append("evergreen_tree")
#oomp_word_dict_words.append("deciduous_tree")
oomp_word_dict_words.append("chestnut")
#oomp_word_dict_words.append("seedling")
oomp_word_dict_words.append("blossom")
#oomp_word_dict_words.append("ear_of_rice")
oomp_word_dict_words.append("shell")
#oomp_word_dict_words.append("globe_with_meridians")
#oomp_word_dict_words.append("sun_with_face")
#oomp_word_dict_words.append("full_moon_with_face")
#oomp_word_dict_words.append("new_moon_with_face")
oomp_word_dict_words.append("new_moon")
#oomp_word_dict_words.append("waxing_crescent_moon")
#oomp_word_dict_words.append("first_quarter_moon")
#oomp_word_dict_words.append("waxing_gibbous_moon")
#oomp_word_dict_words.append("full_moon")
#oomp_word_dict_words.append("waning_gibbous_moon")
#oomp_word_dict_words.append("last_quarter_moon")
#oomp_word_dict_words.append("waning_crescent_moon")
#oomp_word_dict_words.append("last_quarter_moon_with_face")
#oomp_word_dict_words.append("first_quarter_moon_with_face")
oomp_word_dict_words.append("moon")
#oomp_word_dict_words.append("earth_africa")
#oomp_word_dict_words.append("earth_americas")
#oomp_word_dict_words.append("earth_asia")
#oomp_word_dict_words.append("volcano")
#oomp_word_dict_words.append("milky_way")
#oomp_word_dict_words.append("partly_sunny")
#oomp_word_dict_words.append("octocat")
oomp_word_dict_words.append("squirrel")
oomp_word_dict_words.append("bamboo")
#oomp_word_dict_words.append("gift_heart")
oomp_word_dict_words.append("dolls")
#oomp_word_dict_words.append("school_satchel")
#oomp_word_dict_words.append("mortar_board")
oomp_word_dict_words.append("flags")
oomp_word_dict_words.append("fireworks")
#oomp_word_dict_words.append("sparkler")
#oomp_word_dict_words.append("wind_chime")
#oomp_word_dict_words.append("rice_scene")
#oomp_word_dict_words.append("jack_o_lantern")
oomp_word_dict_words.append("ghost")
oomp_word_dict_words.append("santa")
#oomp_word_dict_words.append("christmas_tree")
oomp_word_dict_words.append("gift")
oomp_word_dict_words.append("bell")
#oomp_word_dict_words.append("no_bell")
#oomp_word_dict_words.append("tanabata_tree")
#oomp_word_dict_words.append("tada")
#oomp_word_dict_words.append("confetti_ball")
oomp_word_dict_words.append("balloon")
#oomp_word_dict_words.append("crystal_ball")
#oomp_word_dict_words.append("cd")
#oomp_word_dict_words.append("dvd")
#oomp_word_dict_words.append("floppy_disk")
oomp_word_dict_words.append("camera")
#oomp_word_dict_words.append("video_camera")
#oomp_word_dict_words.append("movie_camera")
oomp_word_dict_words.append("computer")
oomp_word_dict_words.append("tv")
#oomp_word_dict_words.append("iphone")
oomp_word_dict_words.append("phone")
#oomp_word_dict_words.append("telephone")
#oomp_word_dict_words.append("telephone_receiver")
#oomp_word_dict_words.append("pager")
oomp_word_dict_words.append("fax")
#oomp_word_dict_words.append("minidisc")
#oomp_word_dict_words.append("vhs")
#oomp_word_dict_words.append("sound")
oomp_word_dict_words.append("speaker")
#oomp_word_dict_words.append("mute")
#oomp_word_dict_words.append("loudspeaker")
#oomp_word_dict_words.append("mega")
oomp_word_dict_words.append("hourglass")
#oomp_word_dict_words.append("hourglass_flowing_sand")
#oomp_word_dict_words.append("alarm_clock")
oomp_word_dict_words.append("watch")
oomp_word_dict_words.append("radio")
#oomp_word_dict_words.append("satellite")
#oomp_word_dict_words.append("loop")
#oomp_word_dict_words.append("mag")
#oomp_word_dict_words.append("mag_right")
#oomp_word_dict_words.append("unlock")
oomp_word_dict_words.append("lock")
#oomp_word_dict_words.append("lock_with_ink_pen")
#oomp_word_dict_words.append("closed_lock_with_key")
oomp_word_dict_words.append("key")
oomp_word_dict_words.append("bulb")
#oomp_word_dict_words.append("flashlight")
#oomp_word_dict_words.append("high_brightness")
#oomp_word_dict_words.append("low_brightness")
#oomp_word_dict_words.append("electric_plug")
#oomp_word_dict_words.append("battery")
#oomp_word_dict_words.append("calling")
#oomp_word_dict_words.append("email")
#oomp_word_dict_words.append("mailbox")
#oomp_word_dict_words.append("postbox")
oomp_word_dict_words.append("bath")
#oomp_word_dict_words.append("bathtub")
#oomp_word_dict_words.append("shower")
oomp_word_dict_words.append("toilet")
oomp_word_dict_words.append("wrench")
#oomp_word_dict_words.append("nut_and_bolt")
oomp_word_dict_words.append("hammer")
#oomp_word_dict_words.append("seat")
#oomp_word_dict_words.append("moneybag")
#oomp_word_dict_words.append("yen")
#oomp_word_dict_words.append("dollar")
#oomp_word_dict_words.append("pound")
#oomp_word_dict_words.append("euro")
#oomp_word_dict_words.append("credit_card")
#oomp_word_dict_words.append("money_with_wings")
#oomp_word_dict_words.append("e-mail")
#oomp_word_dict_words.append("inbox_tray")
#oomp_word_dict_words.append("outbox_tray")
oomp_word_dict_words.append("envelope")
#oomp_word_dict_words.append("incoming_envelope")
#oomp_word_dict_words.append("postal_horn")
#oomp_word_dict_words.append("mailbox_closed")
#oomp_word_dict_words.append("mailbox_with_mail")
#oomp_word_dict_words.append("mailbox_with_no_mail")
oomp_word_dict_words.append("door")
#oomp_word_dict_words.append("smoking")
#oomp_word_dict_words.append("bomb")
#oomp_word_dict_words.append("gun")
#oomp_word_dict_words.append("hocho")
oomp_word_dict_words.append("pill")
#oomp_word_dict_words.append("syringe")
#oomp_word_dict_words.append("page_facing_up")
#oomp_word_dict_words.append("page_with_curl")
#oomp_word_dict_words.append("bookmark_tabs")
#oomp_word_dict_words.append("bar_chart")
#oomp_word_dict_words.append("chart_with_upwards_trend")
#oomp_word_dict_words.append("chart_with_downwards_trend")
oomp_word_dict_words.append("scroll")
oomp_word_dict_words.append("clipboard")
oomp_word_dict_words.append("calendar")
#oomp_word_dict_words.append("date")
#oomp_word_dict_words.append("card_index")
#oomp_word_dict_words.append("file_folder")
#oomp_word_dict_words.append("open_file_folder")
oomp_word_dict_words.append("scissors")
oomp_word_dict_words.append("pushpin")
oomp_word_dict_words.append("paperclip")
#oomp_word_dict_words.append("black_nib")
#oomp_word_dict_words.append("pencil2")
#oomp_word_dict_words.append("straight_ruler")
#oomp_word_dict_words.append("triangular_ruler")
#oomp_word_dict_words.append("closed_book")
#oomp_word_dict_words.append("green_book")
#oomp_word_dict_words.append("blue_book")
#oomp_word_dict_words.append("orange_book")
#oomp_word_dict_words.append("notebook")
#oomp_word_dict_words.append("notebook_with_decorative_cover")
#oomp_word_dict_words.append("ledger")
oomp_word_dict_words.append("books")
#oomp_word_dict_words.append("bookmark")
#oomp_word_dict_words.append("name_badge")
oomp_word_dict_words.append("microscope")
oomp_word_dict_words.append("telescope")
#oomp_word_dict_words.append("newspaper")
#oomp_word_dict_words.append("football")
oomp_word_dict_words.append("basketball")
#oomp_word_dict_words.append("soccer")
oomp_word_dict_words.append("baseball")
oomp_word_dict_words.append("tennis")
#oomp_word_dict_words.append("8ball")
#oomp_word_dict_words.append("rugby_football")
oomp_word_dict_words.append("bowling")
oomp_word_dict_words.append("golf")
#oomp_word_dict_words.append("mountain_bicyclist")
#oomp_word_dict_words.append("bicyclist")
#oomp_word_dict_words.append("horse_racing")
#oomp_word_dict_words.append("snowboarder")
#oomp_word_dict_words.append("swimmer")
#oomp_word_dict_words.append("surfer")
oomp_word_dict_words.append("ski")
oomp_word_dict_words.append("spades")
oomp_word_dict_words.append("hearts")
oomp_word_dict_words.append("clubs")
oomp_word_dict_words.append("diamonds")
#oomp_word_dict_words.append("gem")
oomp_word_dict_words.append("ring")
oomp_word_dict_words.append("trophy")
#oomp_word_dict_words.append("musical_score")
#oomp_word_dict_words.append("musical_keyboard")
oomp_word_dict_words.append("violin")
#oomp_word_dict_words.append("space_invader")
#oomp_word_dict_words.append("video_game")
#oomp_word_dict_words.append("black_joker")
#oomp_word_dict_words.append("flower_playing_cards")
#oomp_word_dict_words.append("game_die")
#oomp_word_dict_words.append("dart")
#oomp_word_dict_words.append("mahjong")
#oomp_word_dict_words.append("clapper")
#oomp_word_dict_words.append("memo")
oomp_word_dict_words.append("pencil")
oomp_word_dict_words.append("book")
#oomp_word_dict_words.append("art")
#oomp_word_dict_words.append("microphone")
oomp_word_dict_words.append("headphones")
oomp_word_dict_words.append("trumpet")
#oomp_word_dict_words.append("saxophone")
oomp_word_dict_words.append("guitar")
oomp_word_dict_words.append("shoe")
oomp_word_dict_words.append("sandal")
#oomp_word_dict_words.append("high_heel")
oomp_word_dict_words.append("lipstick")
oomp_word_dict_words.append("boot")
oomp_word_dict_words.append("shirt")
#oomp_word_dict_words.append("tshirt")
#oomp_word_dict_words.append("necktie")
#oomp_word_dict_words.append("womans_clothes")
oomp_word_dict_words.append("dress")
#oomp_word_dict_words.append("running_shirt_with_sash")
oomp_word_dict_words.append("jeans")
#oomp_word_dict_words.append("kimono")
#oomp_word_dict_words.append("bikini")
#oomp_word_dict_words.append("ribbon")
oomp_word_dict_words.append("tophat")
oomp_word_dict_words.append("crown")
#oomp_word_dict_words.append("womans_hat")
#oomp_word_dict_words.append("mans_shoe")
#oomp_word_dict_words.append("closed_umbrella")
oomp_word_dict_words.append("briefcase")
oomp_word_dict_words.append("handbag")
#oomp_word_dict_words.append("pouch")
#oomp_word_dict_words.append("purse")
oomp_word_dict_words.append("eyeglasses")
#oomp_word_dict_words.append("fishing_pole_and_fish")
oomp_word_dict_words.append("coffee")
oomp_word_dict_words.append("tea")
#oomp_word_dict_words.append("sake")
#oomp_word_dict_words.append("baby_bottle")
oomp_word_dict_words.append("beer")
#oomp_word_dict_words.append("beers")
#oomp_word_dict_words.append("cocktail")
#oomp_word_dict_words.append("tropical_drink")
#oomp_word_dict_words.append("wine_glass")
#oomp_word_dict_words.append("fork_and_knife")
oomp_word_dict_words.append("pizza")
oomp_word_dict_words.append("hamburger")
oomp_word_dict_words.append("fries")
#oomp_word_dict_words.append("poultry_leg")
#oomp_word_dict_words.append("meat_on_bone")
oomp_word_dict_words.append("spaghetti")
oomp_word_dict_words.append("curry")
#oomp_word_dict_words.append("fried_shrimp")
#oomp_word_dict_words.append("bento")
oomp_word_dict_words.append("sushi")
#oomp_word_dict_words.append("fish_cake")
#oomp_word_dict_words.append("rice_ball")
#oomp_word_dict_words.append("rice_cracker")
oomp_word_dict_words.append("rice")
oomp_word_dict_words.append("ramen")
#oomp_word_dict_words.append("stew")
#oomp_word_dict_words.append("oden")
#oomp_word_dict_words.append("dango")
oomp_word_dict_words.append("egg")
oomp_word_dict_words.append("bread")
oomp_word_dict_words.append("doughnut")
#oomp_word_dict_words.append("custard")
#oomp_word_dict_words.append("icecream")
#oomp_word_dict_words.append("ice_cream")
#oomp_word_dict_words.append("shaved_ice")
oomp_word_dict_words.append("birthday")
oomp_word_dict_words.append("cake")
oomp_word_dict_words.append("cookie")
#oomp_word_dict_words.append("chocolate_bar")
oomp_word_dict_words.append("candy")
oomp_word_dict_words.append("lollipop")
oomp_word_dict_words.append("honey_pot")
oomp_word_dict_words.append("apple")
#oomp_word_dict_words.append("green_apple")
#oomp_word_dict_words.append("tangerine")
oomp_word_dict_words.append("lemon")
oomp_word_dict_words.append("cherries")
oomp_word_dict_words.append("grapes")
oomp_word_dict_words.append("watermelon")
oomp_word_dict_words.append("strawberry")
oomp_word_dict_words.append("peach")
oomp_word_dict_words.append("melon")
oomp_word_dict_words.append("banana")
oomp_word_dict_words.append("pear")
oomp_word_dict_words.append("pineapple")
#oomp_word_dict_words.append("sweet_potato")
#oomp_word_dict_words.append("eggplant")
oomp_word_dict_words.append("tomato")
oomp_word_dict_words.append("corn")
oomp_word_dict_words.append("house")
#oomp_word_dict_words.append("house_with_garden")
oomp_word_dict_words.append("school")
oomp_word_dict_words.append("office")
#oomp_word_dict_words.append("post_office")
oomp_word_dict_words.append("hospital")
oomp_word_dict_words.append("bank")
#oomp_word_dict_words.append("convenience_store")
#oomp_word_dict_words.append("love_hotel")
oomp_word_dict_words.append("hotel")
#oomp_word_dict_words.append("wedding")
#oomp_word_dict_words.append("church")
#oomp_word_dict_words.append("department_store")
#oomp_word_dict_words.append("european_post_office")
#oomp_word_dict_words.append("city_sunrise")
#oomp_word_dict_words.append("city_sunset")
#oomp_word_dict_words.append("japanese_castle")
#oomp_word_dict_words.append("european_castle")
oomp_word_dict_words.append("tent")
oomp_word_dict_words.append("factory")
#oomp_word_dict_words.append("tokyo_tower")
#oomp_word_dict_words.append("japan")
#oomp_word_dict_words.append("mount_fuji")
#oomp_word_dict_words.append("sunrise_over_mountains")
#oomp_word_dict_words.append("sunrise")
oomp_word_dict_words.append("stars")
#oomp_word_dict_words.append("statue_of_liberty")
#oomp_word_dict_words.append("bridge_at_night")
#oomp_word_dict_words.append("carousel_horse")
oomp_word_dict_words.append("rainbow")
#oomp_word_dict_words.append("ferris_wheel")
oomp_word_dict_words.append("fountain")
#oomp_word_dict_words.append("roller_coaster")
oomp_word_dict_words.append("ship")
#oomp_word_dict_words.append("speedboat")
oomp_word_dict_words.append("boat")
oomp_word_dict_words.append("sailboat")
oomp_word_dict_words.append("rowboat")
oomp_word_dict_words.append("anchor")
oomp_word_dict_words.append("rocket")
oomp_word_dict_words.append("airplane")
oomp_word_dict_words.append("helicopter")
#oomp_word_dict_words.append("steam_locomotive")
oomp_word_dict_words.append("tram")
#oomp_word_dict_words.append("mountain_railway")
oomp_word_dict_words.append("bike")
#oomp_word_dict_words.append("aerial_tramway")
#oomp_word_dict_words.append("suspension_railway")
#oomp_word_dict_words.append("mountain_cableway")
oomp_word_dict_words.append("tractor")
#oomp_word_dict_words.append("blue_car")
#oomp_word_dict_words.append("oncoming_automobile")
oomp_word_dict_words.append("car")
#oomp_word_dict_words.append("red_car")
oomp_word_dict_words.append("taxi")
#oomp_word_dict_words.append("oncoming_taxi")
#oomp_word_dict_words.append("articulated_lorry")
oomp_word_dict_words.append("bus")
#oomp_word_dict_words.append("oncoming_bus")
#oomp_word_dict_words.append("rotating_light")
#oomp_word_dict_words.append("police_car")
#oomp_word_dict_words.append("oncoming_police_car")
#oomp_word_dict_words.append("fire_engine")
oomp_word_dict_words.append("ambulance")
#oomp_word_dict_words.append("minibus")
oomp_word_dict_words.append("truck")
oomp_word_dict_words.append("train")
#oomp_word_dict_words.append("station")
#oomp_word_dict_words.append("train2")
#oomp_word_dict_words.append("bullettrain_front")
#oomp_word_dict_words.append("bullettrain_side")
#oomp_word_dict_words.append("light_rail")
#oomp_word_dict_words.append("monorail")
#oomp_word_dict_words.append("railway_car")
#oomp_word_dict_words.append("trolleybus")
oomp_word_dict_words.append("ticket")
#oomp_word_dict_words.append("fuelpump")
#oomp_word_dict_words.append("vertical_traffic_light")
#oomp_word_dict_words.append("traffic_light")
#oomp_word_dict_words.append("warning")
#oomp_word_dict_words.append("construction")
#oomp_word_dict_words.append("beginner")
#oomp_word_dict_words.append("atm")
#oomp_word_dict_words.append("slot_machine")
#oomp_word_dict_words.append("busstop")
#oomp_word_dict_words.append("barber")
#oomp_word_dict_words.append("hotsprings")
#oomp_word_dict_words.append("checkered_flag")
#oomp_word_dict_words.append("crossed_flags")
#oomp_word_dict_words.append("izakaya_lantern")
#oomp_word_dict_words.append("moyai")
#oomp_word_dict_words.append("circus_tent")
#oomp_word_dict_words.append("performing_arts")
#oomp_word_dict_words.append("round_pushpin")
#oomp_word_dict_words.append("triangular_flag_on_post")
#oomp_word_dict_words.append("jp")
#oomp_word_dict_words.append("kr")
#oomp_word_dict_words.append("cn")
#oomp_word_dict_words.append("us")
#oomp_word_dict_words.append("fr")
#oomp_word_dict_words.append("es")
#oomp_word_dict_words.append("it")
#oomp_word_dict_words.append("ru")
# oomp_word_dict_words.append("gb")
# oomp_word_dict_words.append("uk")
# oomp_word_dict_words.append("de")
oomp_word_dict_words.append("one")
oomp_word_dict_words.append("two")
oomp_word_dict_words.append("three")
oomp_word_dict_words.append("four")
oomp_word_dict_words.append("five")
oomp_word_dict_words.append("six")
oomp_word_dict_words.append("seven")
oomp_word_dict_words.append("eight")
oomp_word_dict_words.append("nine")
# oomp_word_dict_words.append("keycap_ten")
# oomp_word_dict_words.append("1234")
# oomp_word_dict_words.append("zero")
# oomp_word_dict_words.append("hash")
# oomp_word_dict_words.append("symbols")
# oomp_word_dict_words.append("arrow_backward")
# oomp_word_dict_words.append("arrow_down")
# oomp_word_dict_words.append("arrow_forward")
# oomp_word_dict_words.append("arrow_left")
# oomp_word_dict_words.append("capital_abcd")
# oomp_word_dict_words.append("abcd")
# oomp_word_dict_words.append("abc")
# oomp_word_dict_words.append("arrow_lower_left")
# oomp_word_dict_words.append("arrow_lower_right")
# oomp_word_dict_words.append("arrow_right")
# oomp_word_dict_words.append("arrow_up")
# oomp_word_dict_words.append("arrow_upper_left")
# oomp_word_dict_words.append("arrow_upper_right")
# oomp_word_dict_words.append("arrow_double_down")
# oomp_word_dict_words.append("arrow_double_up")
# oomp_word_dict_words.append("arrow_down_small")
# oomp_word_dict_words.append("arrow_heading_down")
# oomp_word_dict_words.append("arrow_heading_up")
# oomp_word_dict_words.append("leftwards_arrow_with_hook")
# oomp_word_dict_words.append("arrow_right_hook")
# oomp_word_dict_words.append("left_right_arrow")
# oomp_word_dict_words.append("arrow_up_down")
# oomp_word_dict_words.append("arrow_up_small")
# oomp_word_dict_words.append("arrows_clockwise")
# oomp_word_dict_words.append("arrows_counterclockwise")
# oomp_word_dict_words.append("rewind")
# oomp_word_dict_words.append("fast_forward")
# oomp_word_dict_words.append("information_source")
oomp_word_dict_words.append("ok")
# oomp_word_dict_words.append("twisted_rightwards_arrows")
# oomp_word_dict_words.append("repeat")
# oomp_word_dict_words.append("repeat_one")
# oomp_word_dict_words.append("new")
# oomp_word_dict_words.append("top")
oomp_word_dict_words.append("up")
# oomp_word_dict_words.append("cool")
# oomp_word_dict_words.append("free")
# oomp_word_dict_words.append("ng")
# oomp_word_dict_words.append("cinema")
# oomp_word_dict_words.append("koko")
# oomp_word_dict_words.append("signal_strength")
# oomp_word_dict_words.append("u5272")
# oomp_word_dict_words.append("u5408")
# oomp_word_dict_words.append("u55b6")
# oomp_word_dict_words.append("u6307")
# oomp_word_dict_words.append("u6708")
# oomp_word_dict_words.append("u6709")
# oomp_word_dict_words.append("u6e80")
# oomp_word_dict_words.append("u7121")
# oomp_word_dict_words.append("u7533")
# oomp_word_dict_words.append("u7a7a")
# oomp_word_dict_words.append("u7981")
# oomp_word_dict_words.append("sa")
# oomp_word_dict_words.append("restroom")
# oomp_word_dict_words.append("mens")
# oomp_word_dict_words.append("womens")
# oomp_word_dict_words.append("baby_symbol")
# oomp_word_dict_words.append("no_smoking")
oomp_word_dict_words.append("parking")
# oomp_word_dict_words.append("wheelchair")
# oomp_word_dict_words.append("metro")
# oomp_word_dict_words.append("baggage_claim")
# oomp_word_dict_words.append("accept")
# oomp_word_dict_words.append("wc")
# oomp_word_dict_words.append("potable_water")
# oomp_word_dict_words.append("put_litter_in_its_place")
# oomp_word_dict_words.append("secret")
# oomp_word_dict_words.append("congratulations")
# oomp_word_dict_words.append("m")
# oomp_word_dict_words.append("passport_control")
# oomp_word_dict_words.append("left_luggage")
# oomp_word_dict_words.append("customs")
# oomp_word_dict_words.append("ideograph_advantage")
# oomp_word_dict_words.append("cl")
# oomp_word_dict_words.append("sos")
# oomp_word_dict_words.append("id")
# oomp_word_dict_words.append("no_entry_sign")
# oomp_word_dict_words.append("underage")
# oomp_word_dict_words.append("no_mobile_phones")
# oomp_word_dict_words.append("do_not_litter")
# oomp_word_dict_words.append("non-potable_water")
# oomp_word_dict_words.append("no_bicycles")
# oomp_word_dict_words.append("no_pedestrians")
# oomp_word_dict_words.append("children_crossing")
# oomp_word_dict_words.append("no_entry")
# oomp_word_dict_words.append("eight_spoked_asterisk")
# oomp_word_dict_words.append("eight_pointed_black_star")
# oomp_word_dict_words.append("heart_decoration")
# oomp_word_dict_words.append("vs")
# oomp_word_dict_words.append("vibration_mode")
# oomp_word_dict_words.append("mobile_phone_off")
# oomp_word_dict_words.append("chart")
# oomp_word_dict_words.append("currency_exchange")
# oomp_word_dict_words.append("aries")
# oomp_word_dict_words.append("taurus")
# oomp_word_dict_words.append("gemini")
# oomp_word_dict_words.append("cancer")
# oomp_word_dict_words.append("leo")
# oomp_word_dict_words.append("virgo")
# oomp_word_dict_words.append("libra")
# oomp_word_dict_words.append("scorpius")
# oomp_word_dict_words.append("sagittarius")
# oomp_word_dict_words.append("capricorn")
# oomp_word_dict_words.append("aquarius")
# oomp_word_dict_words.append("pisces")
# oomp_word_dict_words.append("ophiuchus")
# oomp_word_dict_words.append("six_pointed_star")
# oomp_word_dict_words.append("negative_squared_cross_mark")
# oomp_word_dict_words.append("a")
# oomp_word_dict_words.append("b")
# oomp_word_dict_words.append("ab")
# oomp_word_dict_words.append("o2")
# oomp_word_dict_words.append("diamond_shape_with_a_dot_inside")
oomp_word_dict_words.append("recycle")
# oomp_word_dict_words.append("end")
# oomp_word_dict_words.append("on")
# oomp_word_dict_words.append("soon")
# oomp_word_dict_words.append("clock1")
# oomp_word_dict_words.append("clock130")
# oomp_word_dict_words.append("clock10")
# oomp_word_dict_words.append("clock1030")
# oomp_word_dict_words.append("clock11")
# oomp_word_dict_words.append("clock1130")
# oomp_word_dict_words.append("clock12")
# oomp_word_dict_words.append("clock1230")
# oomp_word_dict_words.append("clock2")
# oomp_word_dict_words.append("clock230")
# oomp_word_dict_words.append("clock3")
# oomp_word_dict_words.append("clock330")
# oomp_word_dict_words.append("clock4")
# oomp_word_dict_words.append("clock430")
# oomp_word_dict_words.append("clock5")
# oomp_word_dict_words.append("clock530")
# oomp_word_dict_words.append("clock6")
# oomp_word_dict_words.append("clock630")
# oomp_word_dict_words.append("clock7")
# oomp_word_dict_words.append("clock730")
# oomp_word_dict_words.append("clock8")
# oomp_word_dict_words.append("clock830")
# oomp_word_dict_words.append("clock9")
# oomp_word_dict_words.append("clock930")
# oomp_word_dict_words.append("heavy_dollar_sign")
# oomp_word_dict_words.append("copyright")
# oomp_word_dict_words.append("registered")
# oomp_word_dict_words.append("tm")
# oomp_word_dict_words.append("x")
# oomp_word_dict_words.append("heavy_exclamation_mark")
# oomp_word_dict_words.append("bangbang")
# oomp_word_dict_words.append("interrobang")
# oomp_word_dict_words.append("o")
# oomp_word_dict_words.append("heavy_multiplication_x")
# oomp_word_dict_words.append("heavy_plus_sign")
# oomp_word_dict_words.append("heavy_minus_sign")
# oomp_word_dict_words.append("heavy_division_sign")
# oomp_word_dict_words.append("white_flower")
# oomp_word_dict_words.append("100")
# oomp_word_dict_words.append("heavy_check_mark")
# oomp_word_dict_words.append("ballot_box_with_check")
# oomp_word_dict_words.append("radio_button")
# oomp_word_dict_words.append("link")
# oomp_word_dict_words.append("curly_loop")
# oomp_word_dict_words.append("wavy_dash")
# oomp_word_dict_words.append("part_alternation_mark")
oomp_word_dict_words.append("trident")
# 

hex_1 = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9","a", "b", "c", "d", "e", "f"]
hex_2 = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9","a", "b", "c", "d", "e", "f"]

index = 0
for h1 in hex_1:
    for h2 in hex_2:
        oomp_word_dict[f"{h1}{h2}"] = oomp_word_dict_words[index]
        index += 1






def get_oomp_word(md5_6, style="string"):
    return_value = ""
    w1 = md5_6[0:2]
    w2 = md5_6[2:4]
    w3 = md5_6[4:6]
    word_1 = oomp_word_dict[w1]
    word_2 = oomp_word_dict[w2]
    word_3 = oomp_word_dict[w3]
    if style == "string":
        return_value = f"{word_1} {word_2} {word_3}"
    if style == "list":
        return_value = [word_1, word_2, word_3]
    if style == "emoji":
        return_value = f":{word_1}: :{word_2}: :{word_3}:"
    if style == "emoji_list":
        return_value = [f":{word_1}:", f":{word_2}:", f":{word_3}:"]


    return return_value


#if run
if __name__ == "__main__":
    #print length of oomp_word_dict_words
    print(f"oomp_word_dict_words length: {len(oomp_word_dict_words)}")